version: '2'

services:
  web:
    image: nginx:latest
    container_name: "tvshownotification_nginx"
    ports:
      - "80:80"
    volumes:
      - ./:/tvshownotification
      - ./nginx/site.conf:/etc/nginx/conf.d/site.conf
    networks:
      tvshownotification-network:
        ipv4_address: 172.18.0.2
    links:
      - php

  php:
    build: php-fpm
    container_name: "tvshownotification_php"
    volumes:
      - ./:/tvshownotification
    networks:
      tvshownotification-network:
        ipv4_address: 172.18.0.3
    links:
      - db

  db:
    image: mysql
    container_name: "tvshownotification_mysql"
    ports:
      - "3306:3306"
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: tvshownotification123
      MYSQL_DATABASE_NAME: tvshownotification
    networks:
      tvshownotification-network:
        ipv4_address: 172.18.0.4

networks:
  tvshownotification-network:
    external: true
